export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_FAILURE = 'GET_CHARACTERS_FAILURE';

export const GET_CHARACTERS_DATA = 'GET_CHARACTERS_DATA';
export const GET_CHARACTERS_DATA_SUCCESS = 'GET_CHARACTERS_DATA_SUCCESS';
export const GET_CHARACTERS_DATA_FAILURE = 'GET_CHARACTERS_DATA_FAILURE';

export const UPDATE_CHARACTER_DATA = 'UPDATE_CHARACTER_DATA';
export const UPDATE_CHARACTER_DATA_SUCCESS = 'UPDATE_CHARACTER_DATA_SUCCESS';
export const UPDATE_CHARACTER_DATA_FAILURE = 'UPDATE_CHARACTER_DATA_FAILURE';

export const ADD_CHARACTER = 'ADD_CHARACTER';
export const ADD_CHARACTER_SUCCESS = 'ADD_CHARACTER_SUCCESS';

export const GET_DUNGEON_DATA = 'GET_DUNGEON_DATA';
export const GET_DUNGEON_DATA_SUCCESS = 'GET_DUNGEON_SUCCESS';
export const GET_DUNGEON_DATA_FAILURE = 'GET_DUNGEON_DATA_FAILURE';

export const GET_COLORS = 'GET_COLORS';
export const GET_COLORS_SUCCESS = 'GET_COLORS_SUCCESS';
export const GET_COLORS_FAILURE = 'GET_COLORS_FAILURE';

export const DELETE_CHARACTER = 'DELETE_CHARACTER'
